import React from 'react';
import { Copy, Check, FileText, Archive } from 'lucide-react';
//@ts-expect-error - JSZip types not available in current TypeScript version
import JSZip from 'jszip';

interface CodeOutputProps {
  generatedCode: string;
  copied: boolean;
  selectedType: string;
  selectedOutputFormat: string;
  selectedLibrary: string;
  selectedSubtype: string;
  onCopy: () => void;
  onGenerateCode: () => string;
}

const CodeOutput: React.FC<CodeOutputProps> = ({
  generatedCode,
  copied,
  selectedType,
  selectedOutputFormat,
  selectedLibrary,
  selectedSubtype,
  onCopy,
  onGenerateCode
}) => {
  const getFileExtension = () => {
    switch (selectedOutputFormat) {
      case 'javascript-embed':
      case 'static-html':
        return 'html';
      case 'drupal-block':
      case 'drupal-controller':
        return 'php';
      default:
        return 'txt';
    }
  };

  const getFileName = () => {
    const timestamp = Date.now();
    const baseName = `drupal-${selectedType}-${selectedSubtype || 'chart'}-${selectedLibrary}`;
    return `${baseName}-${timestamp}`;
  };

  const downloadSingleFile = () => {
    const fileName = `${getFileName()}.${getFileExtension()}`;
    const currentCode = onGenerateCode(); // Regenerate code dynamically
    const blob = new Blob([currentCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadZipFile = async () => {
    const zip = new JSZip();
    const baseName = getFileName();
    
    // Add main file
    const mainFileName = `${baseName}.${getFileExtension()}`;
    const currentCode = onGenerateCode(); // Regenerate code dynamically
    zip.file(mainFileName, currentCode);
    
    // Add README
    const readmeContent = `# ${selectedType.charAt(0).toUpperCase() + selectedType.slice(1)} Chart - ${selectedLibrary}

Generated on: ${new Date().toLocaleString()}

## Configuration
- Chart Type: ${selectedType}
- Subtype: ${selectedSubtype}
- Library: ${selectedLibrary}
- Output Format: ${selectedOutputFormat}

## Usage
This package contains the generated code for your ${selectedType} visualization.

## Files
- ${mainFileName}: Main implementation file
- README.md: This documentation

## Installation
Follow the installation instructions based on your selected output format.

Generated by DrupalDataDotDev
https://www.drupaldata.dev
`;

    zip.file('README.md', readmeContent);
    
    // Add package.json for Drupal formats
    if (selectedOutputFormat === 'drupal-block' || selectedOutputFormat === 'drupal-controller') {
      const packageJson = {
        name: `drupal_${baseName.replace(/-/g, '_')}`,
        type: "drupal-module",
        description: `Generated ${selectedType} chart ${selectedOutputFormat.replace('drupal-', '')} using ${selectedLibrary}`,
        core_version_requirement: "^9 || ^10 || ^11",
        dependencies: [],
        version: "1.0.0"
      };
      zip.file('package.json', JSON.stringify(packageJson, null, 2));
    }
    
    // Generate and download ZIP
    const zipBlob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(zipBlob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${baseName}.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="mt-4 space-y-6">
      {/* IDE-Style Code Editor */}
      <div className="bg-[#1e1e1e] rounded-lg border border-[#3e3e3e] overflow-hidden">
        {/* Editor Header */}
        <div className="bg-[#2d2d30] border-b border-[#3e3e3e] px-4 py-2 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="flex space-x-1">
              <div className="w-3 h-3 bg-[#ff5f57] rounded-full"></div>
              <div className="w-3 h-3 bg-[#ffbd2e] rounded-full"></div>
              <div className="w-3 h-3 bg-[#28ca42] rounded-full"></div>
            </div>
            <span className="text-[#cccccc] text-sm font-mono ml-4">
              {getFileName()}.{getFileExtension()}
            </span>
          </div>
          
          {/* Copy Button - Top Right */}
          <button
            onClick={onCopy}
            className="flex items-center gap-2 px-3 py-1.5 bg-[#0e639c] hover:bg-[#1177bb] text-white text-sm rounded transition-colors duration-200"
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </button>
        </div>

        {/* Code Area */}
        <div className="relative">
          <div className="absolute left-0 top-0 bottom-0 w-12 bg-[#1e1e1e] border-r border-[#3e3e3e] flex flex-col text-[#858585] text-xs font-mono pt-2">
            {generatedCode.split('\n').map((_, index) => (
              <div key={index} className="px-2 text-right leading-5">
                {index + 1}
              </div>
            ))}
          </div>
          <textarea
            value={generatedCode}
            readOnly
            placeholder="Generated code will appear here..."
            className="w-full pl-16 pr-4 py-2 bg-[#1e1e1e] text-[#d4d4d4] font-mono text-sm leading-5 resize-none border-none outline-none min-h-[400px]"
            style={{ 
              fontFamily: "'JetBrains Mono', 'Fira Code', 'Monaco', 'Consolas', monospace",
              tabSize: 2
            }}
          />
        </div>
      </div>

      {/* Download Section */}
      <div className="bg-[#1F2937]/20 dark:bg-[#1F2937]/20 bg-gray-50 rounded-lg p-6 border border-[#3E4C5E] dark:border-[#3E4C5E] border-gray-200">
        <h4 className="text-lg font-semibold text-[#E5F1FF] dark:text-[#E5F1FF] text-gray-900 mb-4">
          Download Options
        </h4>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <button
            onClick={downloadSingleFile}
            className="flex items-center justify-center gap-3 px-6 py-4 bg-[#0074BD] dark:bg-[#0074BD] hover:bg-[#005a94] dark:hover:bg-[#005a94] text-white rounded-lg transition-colors duration-200 font-medium"
          >
            <FileText size={20} />
            <span>Download File</span>
          </button>
          
          <button
            onClick={downloadZipFile}
            className="flex items-center justify-center gap-3 px-6 py-4 bg-gradient-to-r from-[#0074BD] to-[#00C9FF] hover:from-[#005a94] hover:to-[#00b8e6] text-white rounded-lg transition-all duration-200 font-medium"
          >
            <Archive size={20} />
            <span>Download ZIP Package</span>
          </button>
        </div>
        
        <div className="mt-4 text-sm text-[#E5F1FF]/70 dark:text-[#E5F1FF]/70 text-gray-600">
          <p><strong>Single File:</strong> Downloads just the generated code file</p>
          <p><strong>ZIP Package:</strong> Downloads a complete package with code, documentation, and metadata</p>
        </div>
      </div>
    </div>
  );
};

export default CodeOutput; 